### ISSUE TITLE
Facebook Event Fetch Broken

### ISSUE THREAD

**Issue by nvgrw** [icdocsoc/mailgen#4]
Possible API change?

**Comment by nvgrw** [comment]
Will probably have to start scraping – this can be done in `src/fb.js`

**Comment by egnwd** [comment]
I think so, I've been trying to get my script working for the website. I keep getting `400`s.

**Comment by kz** [comment]
From my investigation into this a few months ago, it didn't seem possible to automatically fetch events which the user isn't admin for/going to even if it's visible to them. This was tested without production permissions being approved by Facebook, but it shouldn't make any difference.

**Comment by nvgrw** [comment]
It appears it's now impossible to do this with the Facebook API. Perhaps we should consider deprecating the `<facebook>` functionality.
